# Generated by Django 6.0.3 on 2026-03-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "blood_type",
                    models.CharField(
                        choices=[("A+", "A+"), ("A-", "A-"), ("B+", "B+"), ("B-", "B-"), ("O+", "O+"), ("O-", "O-"), ("AB+", "AB+"), ("AB-", "AB-")],
                        max_length=3,
                    ),
                ),
                ("units_required", models.PositiveIntegerField()),
                ("priority", models.CharField(choices=[("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")], default="normal", max_length=20)),
                ("status", models.CharField(choices=[("open", "Open"), ("matched", "Matched"), ("fulfilled", "Fulfilled"), ("cancelled", "Cancelled")], default="open", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("donor", "Donor"), ("requester", "Requester")], max_length=20)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="DonorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[("A+", "A+"), ("A-", "A-"), ("B+", "B+"), ("B-", "B-"), ("O+", "O+"), ("O-", "O-"), ("AB+", "AB+"), ("AB-", "AB-")],
                        max_length=3,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gender", models.CharField(max_length=20)),
                ("is_available", models.BooleanField(default=True)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("user_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="donor_profile", to="main.userprofile")),
            ],
        ),
        migrations.CreateModel(
            name="RequesterOrganization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization_name", models.CharField(max_length=150)),
                ("organization_type", models.CharField(choices=[("hospital", "Hospital"), ("blood_bank", "Blood Bank")], max_length=20)),
                ("user_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="requester_organization", to="main.userprofile")),
            ],
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="requester",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blood_requests", to="main.requesterorganization"),
        ),
        migrations.CreateModel(
            name="DonationMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("notified", "Notified"), ("accepted", "Accepted"), ("declined", "Declined"), ("completed", "Completed")], default="notified", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("blood_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="main.bloodrequest")),
                ("donor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="main.donorprofile")),
            ],
            options={"unique_together": {("blood_request", "donor")}},
        ),
    ]
